import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import VisibleWrapper from "./wrappers/visibleWraper";
import Footer from "./components/footer";
import Navbar from "./components/navbar";
import { AuthProvider } from "./contexts/authContext";
import { Toaster } from "react-hot-toast";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

export const metadata: Metadata = {
  title: "SST Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={` antialiased ${nunito.variable}`}>
        <AuthProvider>
          <VisibleWrapper>
            <Navbar />
          </VisibleWrapper>
          <Toaster
            toastOptions={{
              success: {
                style: {
                  background: "#37CC95",
                  color: "white",
                  borderRadius: "8px",
                  padding: "16px",
                  boxShadow: "0 4px 14px rgba(0, 0, 0, 0.25)",
                },
                iconTheme: {
                  primary: "white",
                  secondary: "#16a34a",
                },
              },
              error: {
                style: {
                  background: "#ef4444",
                  color: "white",
                  borderRadius: "8px",
                  padding: "16px",
                  boxShadow: "0 4px 14px rgba(0, 0, 0, 0.25)",
                },
                iconTheme: {
                  primary: "white",
                  secondary: "#dc2626",
                },
              },
              position: "top-center",
              duration: 2000,
            }}
          />

          {children}
          <VisibleWrapper>
            <Footer />
          </VisibleWrapper>
        </AuthProvider>
      </body>
    </html>
  );
}
