import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import VisibleWrapper from "./wrappers/visibleWraper";
import Footer from "./components/footer";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

export const metadata: Metadata = {
  title: "SST Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={` antialiased ${nunito.variable}`}>
        {children}
        <VisibleWrapper>
          <Footer />
        </VisibleWrapper>
      </body>
    </html>
  );
}
